# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: upbaws2025
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-image-app

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    BUCKET_NAME: ${file(config.json):S3_IMAGE_BUCKET}
    TABLE_NAME: ${file(config.json):DYNAMODB_TABLE}
    REGION: ${file(config.json):AWS_REGION}
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
        - rekognition:DetectLabels
      Resource:
        - arn:aws:s3:::${file(config.json):S3_IMAGE_BUCKET}/*

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
