# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: upbaws2025
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-image-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ${file(config.json):AWS_REGION}
  environment:
    BUCKET_NAME: ${file(config.json):S3_IMAGE_BUCKET}
    TABLE_NAME: ${file(config.json):DYNAMODB_TABLE_NAME}
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
        - rekognition:DetectLabels
      Resource:
        - arn:aws:s3:::${file(config.json):S3_IMAGE_BUCKET}
        - arn:aws:s3:::${file(config.json):S3_IMAGE_BUCKET}/*
    - Effect: "Allow"
      Action:
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
      Resource: "*"
package:
  exclude:
    - config.json
    - package.json
    - package-lock.json
    - README.md
    - .gitignore
    - .serverless/**
functions:
  raynerGetSignedUrl:
    handler: handler.getSignedUrl
    events:
      - httpApi:
          path: /signed-url
          method: get
  raynerProcessImage:
    handler: recognize.processImage
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:Put
          existing: true
resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - PUT
                - POST
                - GET
                - DELETE
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              MaxAge: 3000
    ImageBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:provider.environment.BUCKET_NAME}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*          
    ImageTagsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: image
            AttributeType: S
        KeySchema:
          - AttributeName: image
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

